#UI nạp thẻ
# Khi dùng nên chỉnh MENU trong config thesieutoc = false
title:
  - "&e&lSOSCRAFT.NET &f| &c&lNẠP THẺ"
chonLoaiThe:
  - "Chọn Loại Thẻ:"
chonGiaThe:
  - "Chọn Giá Thẻ:"
  - "&f&l(&4&l*&f&l) &r&aChọn sai mất thẻ đấy nha!"
input1: # input cho nhập seri
  - "Nhập seri:"
input2: # input cho nhập mã thẻ
  - "Nhập mã thẻ:"
placeholderInput1:
  - "seri tại đây"
placeholderInput2:
  - "mã thẻ tại đây"

# Message - bla bla...
huyNap:
  - "Bạn đã hủy nạp thẻ!"
thieuThongTin:
  - "Thiếu thông tin seri hoặc mã thẻ!"
reload:
  - "reload thành công"
xacnhan:
  - "Xác nhận nạp thẻ"
  - "Bật nút lên!"

#Có thể xóa những loại thẻ ko muốn
loaiThe:
  - "Mobifone"
  - "Viettel"
  - "Vietnamobile"
  - "Zing"
  - "Vinaphone"
  - "Gate"
  - "Garena"


#Có thể xóa những giá thẻ ko muốn (chưa hỗ trợ add màu!)
giaThe:
  - "10000" # 10.000VND
  - "20.000VND"
  - "30000"
  - "50000"
  - "100000"
  - "200000"
  - "300000"
  - "500000"
  - "1000000"

