title: "§e§lSOSCRAFT.NET §f| §c§lNẠP THẺ"
xacnhan: "Vui lòng check kĩ lại thẻ để tránh các trường hợp mất thẻ bạn nhé.\n  §a♦§f Nạp qua kênh §e§lMOMO §f§l(§6§l+30%§f§l)\n§e0796802399\n  §aTrương Nguyễn Anh Khoa"