name: SOSNapthePE
version: '${project.version}'
main: me.anhkhoaaa.sosnapthe.SOSNapthePE
api-version: 1.18
depend: [ floodgate , Thesieutoc]
authors: [ Anhkhoaaa ]

commands:
  napthepe:
    description: "nạp thẻ pe"
    aliases: [ donatepe, dntpe ]
